admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

site:
    resource: "@SiteBundle/Controller/"
    type:     annotation
    prefix:   /

presta_sitemap:
    resource: "@PrestaSitemapBundle/Resources/config/routing.yml"